#
# WebsiteBundle
#
# DefaultController

rclab_website_home:
    path:     /
    defaults: { _controller: RCLABWebsiteBundle:Default:index }

rclab_website_contact:
    path:     /contact
    defaults:  { _controller: RCLABWebsiteBundle:Default:contact }

# AssociationController

rclab_website_association:
    path:     /association
    defaults:  { _controller: RCLABWebsiteBundle:Association:association }

rclab_website_association_edit:
    path:    /association/edit
    defaults: { _controller: RCLABWebsiteBundle:Association:edit }


# repairController

rclab_website_repair:
    path:     /reparations
    defaults:  { _controller: RCLABWebsiteBundle:Repair:repairs }

rclab_website_repair_request:
    path:    /reparations/demande
    defaults: { _controller: RCLABWebsiteBundle:Repair:request }

rclab_website_repair_edit:
    path:    /reparations/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Repair:edit
    requirements:
        id:    \d+

rclab_website_repair_history_user:
    path:    /compte/monHistorique/reparations/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Repair:myHistory
        page:        1
    requirements:
        page:    \d+

rclab_website_repair_history_all:
    path:    /compte/historique/reparations/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Repair:allHistory
        page:        1
    requirements:
        page:    \d+

rclab_website_repair_handle:
    path:    /compte/reparations/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Repair:handle
        page:        1
    requirements:
        page:    \d+

rclab_website_repair_detail:
    path:    /reparations/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Repair:detail
    requirements:
        id:    \d+


# CourseController

rclab_website_course:
    path:     /cours
    defaults:  { _controller: RCLABWebsiteBundle:Course:course }

rclab_website_course_request:
    path:     /cours/demande
    defaults: { _controller: RCLABWebsiteBundle:Course:request }

rclab_website_course_edit:
    path:    /compte/cours/editer/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Course:edit
    requirements:
        id:    \d+

rclab_website_course_valid:
    path:    /compte/cours/valider/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Course:valid
    requirements:
        id:    \d+

rclab_website_course_handle:
    path:    /compte/cours/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Course:handle
        page:        1
    requirements:
        page:    \d+

rclab_website_course_history_user:
    path:    /compte/monHitorique/cours/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Course:myHistory
        page:        1
    requirements:
        page:    \d+

rclab_website_course_history_all:
    path:    /compte/Historique/cours/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Course:allHistory
        page:        1
    requirements:
        page:    \d+

rclab_website_course_detail:
    path:    /cours/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Course:detail
    requirements:
        id:    \d+

rclab_website_course_subscribe:
    path:    /cours/inscription/{id}
    defaults:
         _controller: RCLABWebsiteBundle:Course:subscribe
    requirements:
         id:    \d+

rclab_website_course_unsubscribe:
    path:    /cours/desinscription/{id}
    defaults:
         _controller: RCLABWebsiteBundle:Course:unsubscribe
    requirements:
        id:    \d+

rclab_website_course_refuse:
    path:    /compte/cours/refuser/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Course:refuse
    requirements:
        id:    \d+

# MatiereController

rclab_website_matiere_matieres:
    path:    /cours/matieres
    defaults: { _controller: RCLABWebsiteBundle:Matiere:matieres }

rclab_website_matiere_add:
    path:    /cours/matieres/add
    defaults: { _controller: RCLABWebsiteBundle:Matiere:addMatiere }

rclab_website_matiere_edit:
    path:    /cours/matieres/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Matiere:editMatiere
    requirements:
        id:    \d+

rclab_website_matiere_historise:
    path:    /cours/matieres/historise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Matiere:historiseMatiere
    requirements:
        id:    \d+

rclab_website_matiere_unhistorise:
    path:    /cours/matieres/unhistorise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Matiere:unhistoriseMatiere
    requirements:
        id:    \d+

rclab_website_matiere_remove:
    path:    /cours/matieres/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Matiere:removeMatiere
    requirements:
        id:    \d+

# NiveauController

rclab_website_niveau_niveaux:
    path:    /cours/niveaux
    defaults: { _controller: RCLABWebsiteBundle:Niveau:niveaux }

rclab_website_niveau_add:
    path:    /cours/niveaux/add
    defaults: { _controller: RCLABWebsiteBundle:Niveau:addNiveau }

rclab_website_niveau_edit:
    path:    /cours/niveaux/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Niveau:editNiveau
    requirements:
        id:    \d+

rclab_website_niveau_historise:
    path:    /cours/niveaux/historise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Niveau:historiseNiveau
    requirements:
        id:    \d+

rclab_website_niveau_unhistorise:
    path:    /cours/niveaux/unhistorise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Niveau:unhistoriseNiveau
    requirements:
        id:    \d+

rclab_website_niveau_remove:
    path:    /cours/niveaux/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Niveau:removeNiveau
    requirements:
        id:    \d+

# ActualiteController

rclab_website_actualite:
    path:     /actualite/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:actualite
        page:        1
    requirements:
        page:    \d+

rclab_website_actualite_event_subscribe:
    path:    /actualite/event/subscribe/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:subscribeEvent
    requirements:
        id:    \d+

# news
#rclab_website_actualite_news:
#    path:    /actualite/news/{page}
#    defaults:
#        _controller: RCLABWebsiteBundle:Actualite:news
#        page:        1
#    requirements:
#        page:    \d+

rclab_website_actualite_news_detail:
    path:    /actualite/news/news/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:newsDetail
    requirements:
        id:    \d+

rclab_website_actualite_news_add:
    path:    /actualite/news/add
    defaults: { _controller: RCLABWebsiteBundle:Actualite:addNews }

rclab_website_actualite_news_edit:
    path:    /actualite/news/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:editNews
    requirements:
        id:     \d+

rclab_website_actualite_news_remove:
    path:    /actualite/news/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:removeNews
    requirements:
        id:    \d+

# events
#rclab_website_actualite_events:
#    path:    /actualite/events/{page}
#    defaults:
#        _controller: RCLABWebsiteBundle:Actualite:events
#        page:        1
#    requirements:
#        page:    \d+

rclab_website_actualite_events_detail:
    path:    /actualite/events/event/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:eventDetail
    requirements:
        id:    \d+

rclab_website_actualite_events_add:
        path:    /actualite/events/add
        defaults: { _controller: RCLABWebsiteBundle:Actualite:addEvent }


rclab_website_actualite_events_edit:
    path:    /actualite/events/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:editEvent
    requirements:
        id:    \d+

rclab_website_actualite_events_remove:
    path:    /actualite/events/remove/{id}
    defaults:
         _controller: RCLABWebsiteBundle:Actualite:removeEvent
    requirements:
        id:    \d+

rclab_website_actualite_events_handle:
    path:    /compte/actaulite/events/gerer
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:handleEvents

rclab_website_actualite_events_handleSubscription:
    path:    /compte/actualite/events/gerer/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:handleSubscriptionEvent
    requirements:
        id:    \d+

rclab_website_actualite_events_unsubscribe:
    path:    /compte/actualites/events/gerer/{event}/desinscrire/{user}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:unsubscribeEvent
    requirements:
        event:    \d+
        user:     \d+

rclab_website_actualite_events_subscribe_confirmation:
    path:    /compte/actualites/events/gerer/{event}/inscrire/{user}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:confirmationSubscriptionEvent
    requirements:
        event:    \d+
        user:     \d+

# TDemandeController

rclab_website_tdemandes:
    path:    /typesDemandes
    defaults: { _controller: RCLABWebsiteBundle:TDemande:tDemande }

rclab_website_tdemandes_add:
    path:    /typesDemandes/add
    defaults: { _controller: RCLABWebsiteBundle:TDemande:addTDemande }

rclab_website_tdemandes_edit:
    path:    /typesDemandes/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:TDemande:editTDemande
    requirements:
        id:    \d+

rclab_website_tdemandes_remove:
    path:    /typesDemandes/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:TDemande:removeTDemande
    requirements:
        id:    \d+

rclab_website_tdemandes_historise:
    path:    /typesDemandes/historise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:TDemande:historiseTDemande
    requirements:
        id:    \d+

rclab_website_tdemandes_unhistorise:
    path:    /typesDemandes/unhistorise/{id}
    defaults:
        _controller: RCLABWebsiteBundle:TDemande:unhistoriseTDemande
    requirements:
        id:    \d+

# FonctionController

rclab_website_fonction_list:
    path:    /fonction/list
    defaults: { _controller: RCLABWebsiteBundle:Fonction:fonctions }

rclab_website_fonction_add:
    path:    /fonction/add
    defaults: { _controller: RCLABWebsiteBundle:Fonction:add }

rclab_website_fonction_edit:
    path:    /fonction/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Fonction:edit
    requirements:
         id: \d+

rclab_website_fonction_remove:
    path:    /fonction/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Fonction:remove
    requirements:
         id:     \d+

#
# UserBundle
#

# SecurityController

rclab_user_security_login:
    path:    /connexion
    defaults: { _controller: RCLABUserBundle:Security:login }

# RegistrationController

rclab_user_registration_register:
    path:    /inscription
    defaults: { _controller: RCLABUserBundle:Registration:register }

rclab_user_registration_checkEmail:
    path:    /inscription/verification/{id}
    defaults: { _controller: RCLABUserBundle:Registration:checkEmail }

# UserController

rclab_user_profile:
    path:    /profile/userinfo
    defaults: { _controller: RCLABUserBundle:User:profile }

rclab_user_users_list:
    path:    /liste_des_utilisateurs
    defaults: { _controller: RCLABUserBundle:User:users }

rclab_user_photo_reset:
    path:    /gestion_des_utilisateurs/reinitialisation_de_la_photo/{id}
    defaults:
        _controller: RCLABUserBundle:User:resetPhoto
    requirements:
        id:    \d+

rclab_user_edit:
    path:   /gestion_des_utilisateurs/modifier/{id}
    defaults:
        _controller: RCLABUserBundle:User:edit
    requirements:
        id:    \d+

rclab_user_remove:
    path:    /gestion_des_utilisateurs/supprimer/{id}
    defaults:
        _controller: RCLABUserBundle:User:remove
    requirements:
        id:    \d+
#
# FosUserBundle
#

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile