<?php

namespace RCLAB\WebsiteBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMatiere()
    {
        return $this->createQueryBuilder('m')
            ->select('m.matiere')
            ->getQuery()
            ->getArrayResult();
    }
}
