<?php
namespace RCLAB\WebsiteBundle\Repository;
/**
 * EventInscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInscritRepository extends \Doctrine\ORM\EntityRepository
{
}