<?php

namespace RCLAB\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findFocusNewsEvents()
    {
        $sql = "SELECT *, Event.DebutEvent as date FROM Event UNION (SELECT *, News.DebutPublication as date FROM News) ORDER BY date DESC ";

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
    }

}
