<?php

namespace RCLAB\WebsiteBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPersonneStatutByTri($tri)
    {
        $query = $this->_em->createQuery('SELECT * FROM  Personne JOIN Statut WITH Personne.idStatut = Statut.idStatut WHERE Statut.tri <= :tri');
        $query->setParameters(array('tri' => $tri));
        $personnes = $query->getResult();
        return $personnes;
    }

    public function findPersonneFonctionByTri($tri)
    {
         $query = $this
             ->createQueryBuilder('p')
             ->select('p')
             ->join('p.fonction', 'fonction')
             ->addSelect('fonction');

         return $query
             ->where("p.fonction = fonction.id")
             ->andWhere('fonction.tri <= :tri')
             ->setParameter('tri', $tri)
             ->getQuery()
             ->getArrayResult();

    }

}
