<?php /** @noinspection PhpMissingBreakStatementInspection */

/** @noinspection PhpMissingBreakStatementInspection */

namespace RCLAB\UserBundle\Repository;

/**
 * UserAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $role
     * @return array
     */
    public function findUsers($superAdmin)
    {
        $query = $this
            ->createQueryBuilder('u')
            ->leftjoin('u.fonction', 'fonction')
            ->addSelect('fonction')
            ->where('u.enabled = 1');


        if (!$superAdmin) {
            $query
                ->andwhere('u.roles NOT LIKE :role')
                ->setParameter('role', '%ROLE_SUPER_ADMIN%');

       }
        return $query
            ->getQuery()
            ->getArrayResult();

    }

    public function findUserFonctionByTri($tri)
    {
        $query = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->join('u.fonction', 'fonction')
            ->addSelect('fonction');

        return $query
            ->where("u.fonction = fonction.id")
            ->andWhere('fonction.tri <= :tri')
            ->setParameter('tri', $tri)
            ->getQuery()
            ->getArrayResult();

    }
}
